### ISSUE TITLE
抽象话是否可以做最长匹配？

### ISSUE THREAD

**Issue by ZM-J** [gaowanliang/NMSL#1]
譬如以下用例：
```
西交大哥人在美国刚下飞机
```
高度抽象结果：
```
西🍌带哥人在美国刚⬇飞📝
```
这里，`人`没有抽象出来可能是字典的问题，但是`美国`妹有给整明白属实有丶拉跨嗷，👴是默认宁分词结果有分到美国的

**Comment by gaowanliang** [comment]
分词没有问题，词库里没有国家国旗，今天晚上会补上。对于分词，可以进入网页打开控制台进行测试
```javascript
segmentit.doSegment('西交大哥人在美国刚下飞机');
```
可以正常分词为  `西 交 大哥 人 在 美国 刚 下飞机` 由于是纯前端的，而且词库比较旧，效果就这么回事吧,分不出`下` `飞机`很正常，现在还是初代版本，有时间会优化成调用云函数的。
